// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Project1
{
    static partial class ManifestResources
    {
        public static partial class File1
        {
            public const string txt = "Project1.File1.txt";
        }
    }
}
