// <auto-generated/>
#pragma warning disable
#nullable disable

global using static Belp.Build.PseudoKeywords.BoolAlternativeLiterals;
using System.ComponentModel;

namespace Belp.Build.PseudoKeywords;

[EditorBrowsable(EditorBrowsableState.Never)]
internal static class BoolAlternativeLiterals
{
    /// <summary>
    /// A boolean constant for <see langword="false"/>.
    /// </summary>
    public const bool False = false;

    /// <summary>
    /// A boolean constant for <see langword="true"/>.
    /// </summary>
    public const bool True = true;



    /// <summary>
    /// A boolean constant for <see langword="false"/>.
    /// </summary>
    public const bool Off = false;

    /// <summary>
    /// A boolean constant for <see langword="false"/>.
    /// </summary>
    public const bool off = false;

    /// <summary>
    /// A boolean constant for <see langword="true"/>.
    /// </summary>
    public const bool On = true;

    /// <summary>
    /// A boolean constant for <see langword="true"/>.
    /// </summary>
    public const bool on = true;



    /// <summary>
    /// A boolean constant for <see langword="false"/>.
    /// </summary>
    public const bool No = false;

    /// <summary>
    /// A boolean constant for <see langword="false"/>.
    /// </summary>
    public const bool no = false;

    /// <summary>
    /// A boolean constant for <see langword="true"/>.
    /// </summary>
    public const bool Yes = true;

    /// <summary>
    /// A boolean constant for <see langword="true"/>.
    /// </summary>
    public const bool yes = true;
}
