// <auto-generated/>
#pragma warning disable
#nullable disable

global using static Belp.Build.PseudoKeywords.MathLiterals;
using System;
using System.ComponentModel;

namespace Belp.Build.PseudoKeywords;

/// <summary>
/// Provides math literals.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
internal static partial class MathLiterals
{

#pragma warning disable IDE1006 // Naming Styles

    /// <summary>
    /// Gets the golden ratio.
    /// </summary>
    public const double φ = 1.6180339887498948;

    /// <inheritdoc cref="Math.PI" />
    public const double π = Math.PI;

    /// <inheritdoc cref="Math.Tau" />
    public const double τ = Math.Tau;

#pragma warning restore IDE1006 // Naming Styles

}
