// <auto-generated/>
#pragma warning disable
#nullable disable

global using static Belp.Build.PseudoKeywords.NameofExpressionKeywords;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Belp.Build.PseudoKeywords;

[EditorBrowsable(EditorBrowsableState.Never)]
internal static class NameofExpressionKeywords
{

#pragma warning disable IDE1006 // Naming Styles

    /// <summary>
    /// Returns the specified expression's string representation.
    /// </summary>
    /// <param name="expression">The expression.</param>
    /// <param name="expressionString">Do not specify.</param>
    /// <returns>The expression's string representation.</returns>
    public static string nameofexpr<T>(T expression, [CallerArgumentExpression(nameof(expression))] string expressionString = "")
    {
        return expressionString;
    }

#pragma warning restore IDE1006 // Naming Styles

}
