// <auto-generated/>
#pragma warning disable
#nullable disable



#region Integer Types

global using int8 = System.SByte;
global using uint8 = System.Byte;
global using int16 = System.Int16;
global using uint16 = System.UInt16;
global using int32 = System.Int32;
global using uint32 = System.UInt32;
global using int64 = System.Int64;
global using uint64 = System.UInt64;

#endregion



#region Floating-Point Types

global using half = System.Half;
global using fp16 = System.Half;
global using float16 = System.Half;
global using single = System.Single;
global using fp32 = System.Single;
global using float32 = System.Single;
global using fp64 = System.Double;
global using float64 = System.Double;

#endregion



#region Other Numeric Types

global using bigint = System.Numerics.BigInteger;
global using complex = System.Numerics.Complex;

#endregion



#region Temporal Types

global using datetime = System.DateTime;
global using date = System.DateOnly;
global using time = System.TimeOnly;
global using timespan = System.TimeSpan;

#endregion



#region Other Types

global using boolean = System.Boolean;

#endregion
