// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test.Project1
{
    static partial class ManifestResources
    {
        public static partial class DirB
        {
            public static partial class File5
            {
                public const string txt = "Test.Project1.DirB.File5.txt";
            }
        }
    }
}
