// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test.Project1
{
    static partial class ManifestResources
    {
        public static partial class DirA
        {
            public static partial class File3
            {
                public const string txt = "Test.Project1.DirA.File3.txt";
            }
        }
    }
}
