// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test.Project1
{
    static partial class ManifestResources
    {
        public static partial class DirA
        {
            public static partial class DirAA
            {
                public static partial class File4
                {
                    public const string ini = "Test.Project1.DirA.DirAA.File4.ini";
                }
            }
        }
    }
}
