// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test.Project1
{
    static partial class ManifestResources
    {
        public static partial class DirA
        {
            public static global::System.Collections.Generic.IReadOnlyList<string> Resources { get; } = new string[]
            {
                """"Test.Project1.DirA.DirAA.File4.ini"""",
                """"Test.Project1.DirA.File3.txt"""",
            };
        }
    }
}
