// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test
{
    static partial class ManifestResources
    {
        public static global::System.Collections.Generic.IReadOnlyList<string> Resources { get; } = new string[]
        {
            """"Test.Project1.DirA.DirAA.File4.ini"""",
            """"Test.Project1.DirA.File3.txt"""",
            """"Test.Project1.DirB.File5.txt"""",
            """"Test.Project1.File1.txt"""",
            """"Test.Project1.File2.txt"""",
        };
    }
}
