// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Project1
{
    static partial class ManifestResources
    {
        public static partial class DirA
        {
            public static partial class File2
            {
                public const string json = "Project1.DirA.File2.json";
            }
        }
    }
}
