// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Project1
{
    static partial class ManifestResources
    {
        public static partial class DirA
        {
            public static global::System.Collections.Generic.IReadOnlyList<string> Resources { get; } = new string[]
            {
                """"Project1.DirA.File2.json"""",
            };
        }
    }
}
