// <auto-generated/>
#pragma warning disable
#nullable disable

namespace Test.Project1
{
    static partial class ManifestResources
    {
        public static partial class File2
        {
            public static global::System.Collections.Generic.IReadOnlyList<string> Resources { get; } = new string[]
            {
                """"Test.Project1.File2.txt"""",
            };
        }
    }
}
